# Generated by Django 4.2.5 on 2023-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descripcion_evento',
            field=models.CharField(max_length=100),
        ),
    ]
